see also [Notebook](https://github.com/salgo60/open-data-examples/blob/master/Riksdagens%20ledam%C3%B6ter%20status.ipynb) fetching current status
* this [Notebook](https://github.com/salgo60/Wikidata_riksdagen-corpus/blob/main/Notebook/GetViceTalm%C3%A4n.ipynb)
  * [talman.csv](https://github.com/salgo60/Wikidata_riksdagen-corpus/blob/main/Notebook/talman.csv) intressent_id = WD [P1214](https://www.wikidata.org/wiki/Property:P1214)
* GITHUB [issues/34](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/34)

In [1]:
from datetime import datetime
start_time  = datetime.now()
print("Last run: ", start_time)

Last run:  2022-02-14 18:18:52.249425

In [33]:
import urllib3, json
import pandas as pd 
http = urllib3.PoolManager() 
pd.set_option("display.max.columns", None) 
url ="http://data.riksdagen.se/personlista/?rdlstatus=samtliga&utformat=json&termlista="

r = http.request('GET', url)
data = json.loads(r.data)
dftot = pd.json_normalize(data["personlista"]["person"],record_path=[['personuppdrag', 'uppdrag']],
                          max_level=None)
#dftot = pd.json_normalize(data["personlista"]["person"],
#                          max_level=None,record_path =['personuppdrag'])
#dftot = pd.json_normalize(data["personlista"]["person"],
#                          max_level=None,record_path =['personuppdrag'],
#                          meta=['hangar_guid', 'efternamn','tilltalsnamn'])
dftot.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28134 entries, 0 to 28133
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   organ_kod                28134 non-null  object
 1   roll_kod                 28134 non-null  object
 2   ordningsnummer           28134 non-null  object
 3   status                   28134 non-null  object
 4   typ                      28134 non-null  object
 5   from                     28134 non-null  object
 6   tom                      28134 non-null  object
 7   uppgift                  28134 non-null  object
 8   intressent_id            28134 non-null  object
 9   hangar_id                28134 non-null  object
 10  sortering                28134 non-null  object
 11  organ_sortering          28134 non-null  object
 12  uppdrag_rollsortering    28134 non-null  object
 13  uppdrag_statussortering  28134 non-null  object
dtypes: object(14)
memory usage: 3.0+ MB

In [35]:
dftot

,organ_kod,roll_kod,ordningsnummer,status,typ,from,tom,uppgift,intressent_id,hangar_id,sortering,organ_sortering,uppdrag_rollsortering,uppdrag_statussortering
0,kam,Statsrådsersättare,120,Ersättare,kammaruppdrag,2018-09-24,2022-09-26 10:59:00,[Tomas Eneroth],049290762318,2369327,,10,60,20
1,kam,Statsrådsersättare,183,Ersättare,kammaruppdrag,2017-07-27,2018-09-24 23:59:00,[Tomas Eneroth],049290762318,2369327,,10,60,20
2,kam,Riksdagsledamot,329,Tjänstgörande,kammaruppdrag,2010-10-04,2014-09-29 23:59:00,[{}],049290762318,2369327,10,10,60,10
3,AU,Suppleant,147,,uppdrag,2020-03-18 09:00:00,2022-09-26 10:59:00,[Arbetsmarknadsutskottet],049290762318,2369327,50,150,90,90
4,CU,Suppleant,148,,uppdrag,2020-03-18 09:00:00,2022-09-26 10:59:00,[Civilutskottet],049290762318,2369327,50,150,90,90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28129,EUN,Suppleant,326,,uppdrag,2021-10-13 09:00:00,2021-11-30 12:59:00,[EU-nämnden],0965245623824,3057330,50,170,90,90
28130,kam,Ersättare,201,Ersättare,kammaruppdrag,2021-12-02,2022-02-13 23:59:00,[Carl-Oskar Bohlin],0426843954410,5004068,45,10,60,20
28131,CU,Extra suppleant,0,,uppdrag,2021-12-02 12:01:00,2022-02-13 23:59:00,[Civilutskottet],0426843954410,5004068,55,150,90,90
28132,kam,Statsrådsersättare,200,Ersättare,kammaruppdrag,2022-01-10,2022-09-26 10:59:00,[Peter Hultqvist],023732429721,5116100,,10,60,20
28133,KU,Suppleant,1,,uppdrag,2022-02-01,2022-09-26 10:59:00,[Konstitutionsutskottet],023732429721,5116100,50,150,90,90

In [36]:
dfVice = dftot[dftot["roll_kod"].str.contains("vice talman", case=False)]
#pokemon_games = df.loc[df['Name'].str.contains("pokemon", case=False)]

In [38]:
dfVice.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18 entries, 3591 to 26955
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   organ_kod                18 non-null     object
 1   roll_kod                 18 non-null     object
 2   ordningsnummer           18 non-null     object
 3   status                   18 non-null     object
 4   typ                      18 non-null     object
 5   from                     18 non-null     object
 6   tom                      18 non-null     object
 7   uppgift                  18 non-null     object
 8   intressent_id            18 non-null     object
 9   hangar_id                18 non-null     object
 10  sortering                18 non-null     object
 11  organ_sortering          18 non-null     object
 12  uppdrag_rollsortering    18 non-null     object
 13  uppdrag_statussortering  18 non-null     object
dtypes: object(14)
memory usage: 2.1+ KB

In [39]:
dfVice

,organ_kod,roll_kod,ordningsnummer,status,typ,from,tom,uppgift,intressent_id,hangar_id,sortering,organ_sortering,uppdrag_rollsortering,uppdrag_statussortering
3591,kam,Andre vice talman,30,,talmansuppdrag,2010-10-04,2014-09-29 23:59:00,[{}],0584183916016,2343426,15,10,30,90
4192,kam,Förste vice talman,20,,talmansuppdrag,2003-01-01,2006-10-02 23:59:00,[{}],031005479013,2342682,10,10,20,90
5059,kam,Tredje vice talman,40,,talmansuppdrag,1998-10-05,2002-09-30 23:59:00,[{}],0699354970600,2342508,20,10,40,90
5916,kam,Förste vice talman,20,,talmansuppdrag,2006-10-02,2010-10-04 23:59:00,[{}],079095006519,2342630,10,10,20,90
6918,kam,Andre vice talman,30,,talmansuppdrag,1998-10-05,2002-09-30 23:59:00,[{}],0163254848207,2342470,15,10,30,90
7151,kam,Förste vice talman,20,,talmansuppdrag,2010-10-04,2014-09-29 23:59:00,[{}],0235974887200,2342494,10,10,20,90
7349,kam,Förste vice talman,20,,talmansuppdrag,2018-09-24,2022-09-26 10:59:00,[{}],0252067342313,2342918,10,10,20,90
12008,kam,Andre vice talman,30,,talmansuppdrag,2018-09-24,2022-09-26 10:59:00,[{}],0122987223112,3057161,15,10,30,90
14128,kam,Tredje vice talman,40,,talmansuppdrag,2012-10-01,2014-09-29 23:59:00,[{}],09812885803,2342264,20,10,40,90
16525,kam,Andre vice talman,30,,talmansuppdrag,2014-09-29,2018-09-24 23:59:00,[{}],0452755722723,2369312,15,10,30,90
17484,kam,Tredje vice talman,40,,talmansuppdrag,2014-09-29,2018-09-24 23:59:00,[{}],0182190010218,2343207,20,10,40,90
18952,kam,Förste vice talman,20,,talmansuppdrag,1998-10-05,2002-09-30 23:59:00,[{}],037063714405,2342286,10,10,20,90
19245,kam,Andre vice talman,30,,talmansuppdrag,2006-10-02,2010-10-04 23:59:00,[{}],0185503778507,2342311,15,10,30,90
20448,kam,Tredje vice talman,40,,talmansuppdrag,2010-10-04,2012-09-30 23:59:00,[{}],0367418588113,2343043,20,10,40,90
20450,kam,Tredje vice talman,40,,talmansuppdrag,2006-10-02,2010-10-04 23:59:00,[{}],0367418588113,2343043,20,10,40,90
22164,kam,Tredje vice talman,40,,talmansuppdrag,2018-09-24,2022-09-26 10:59:00,[{}],0155487380917,2342851,20,10,40,90
26832,kam,Förste vice talman,20,,talmansuppdrag,2017-10-11,2018-09-24 23:59:00,[{}],0714579775816,2343077,10,10,20,90
26955,kam,Förste vice talman,20,,talmansuppdrag,2014-09-29,2017-10-10 23:59:00,[{}],0956595590924,2343564,10,10,20,90

In [40]:
dfVice.to_csv("talman.csv")

In [ ]:
#